### ISSUE TITLE
File input element

### ISSUE THREAD

**Issue by g-ariunbold** [codaxy/cxjs#481]
Is there a widget for `<input type="file" >` which I can use within a `<form>` element along with other input elements? I tried writing `<input type="file" >` myself in JSX, but it gets converted to `<input type="text" >`.

There is **Upload button** widget, but it seems to work by itself (i.e. when a file is chosen, it gets uploaded) not within a form element. Is there a way to make **Upload button** work in form?

**Comment by mstijak** [comment]
Actually, none of the CxJS widgets works with `<form>` elements.  Since CxJS is a framework for single page applications, classic form submit is not supported. Forms are submitted using AJAX calls.
Regarding file uploads, the server should take a file, store it and send back an identifier (file path or id).
That identifier should be sent back to the server when the form is submitted.
