### ISSUE TITLE
TextField missing keystrokes

### ISSUE THREAD

**Issue by tymarats** [codaxy/cxjs#530]
This is an interesting one that's been present for quite a while. Take a look at this example:

https://codesandbox.io/s/mmm0y48r49

If you start typing something in the first, or the second text field, it will always miss the first keystroke (e.g. if you type "text", it will contain "ext"). And only once after the page load-- afterward, it works fine. It's an annoyance e.g. in cases when you want debounced filtering since you need to rely on debounced filter triggers, and that's not very clean when there are multiple filters (debounced and otherwise) involved. 

I will try to give it a deeper look and provide a PR, but at this moment, I'm not sure exactly where to start.

**Comment by mstijak** [comment]
I'm going to close this as this is the expected behavior.

Unbounded fields should not allow typing. This is now fixed. 

Debounced text fields are problematic as the field has to decide whether to accept changes coming from the store (delayed set) or to keep the text which is currently in the box. That decision could be based on a fact whether the field is focused or not, but that would not work very in every scenario. For that reason, my advice is that reacting on each key and using debounce should be avoided.
