### ISSUE TITLE
Issue with scroll resetting to top on row expanding grid rendered with content resolver component

### ISSUE THREAD

**Issue by BesnikMahmuti-Prosperoware** [codaxy/cxjs#602]
Rendering dynamically a row expanding grid with content resolver is causing an issue. When we scroll down and click on a row to expand it the scroll position is being reset to top. I tried the same with a normal Grid component (not rendering it with Content resolver component it worked fine). I think the issue is with the content resolver component. This component has two properties params-bind and onResolve. I think the issue is with params-bind that is triggering the whole grid to be re-rendered so that is resetting the scroll too.

**Comment by mstijak** [comment]
ContentResolver destroys and re-creates the whole content if params change, in your case the whole grid is being recreated. This is useful when changing grid columns, grouping and similar. You should make sure that grid data is not passed through the content resolver, because when data changes the grid doesn't have to be re-created. Expanding a row should not cause content resolver to trigger a content change.
